### ISSUE TITLE
The problem with the random method

### ISSUE THREAD

**Issue by AaronHuston** [scrazzz/redgifs#5] opened 2022-08-18 14:49 UTC
Hello! Faced some problems with the random method. The following error appears:

**'local variable 'st' referenced before assignment'**

api = redgifs.API()
result = api.search(
    Tags.random(count=1),
    order=Order.best,     
    count=72,
    page=input()                
)

**Comment by scrazzz** [comment] 2022-08-18 15:07
Hey, good catch. Thanks for reporting this bug. Will be fixed asap.

**Comment by anytarseir67** [comment] 2022-08-20 09:04
i'd like to point out that this is not really a bug, this should be the expected behavior. if the "normal" usage of the function results in a list, there is no reason that you should change that for edge cases.

**Comment by scrazzz** [comment] 2022-08-20 09:39
> i'd like to point out that this is not really a bug, this should be the expected behavior. if the "normal" usage of the function results in a list, there is no reason that you should change that for edge cases.

Yes, you're right. I have thought of the same thing too.  But then I have planned to return just the string if `random(n=1)` and return a list of string if n > 1.

This would be easier and clean because sometimes you just want a quick way of getting the result without doing `random(1)[0]` everytime.

Now that you have mentioned it, I'm not sure wheather to keep the random function as-is or to change it.

**Comment by anytarseir67** [comment] 2022-08-22 00:52
> Yes, you're right. I have thought of the same thing too. But then I have planned to return just the string if `random(n=1)` and return a list of string if n > 1.
> 
> ```python
> def random(n: int = 1) Union[str, List[str]:
>     if n == 1:
>         # do fuzzy search here
>         return just_string
> 
>     # normal functioning of method here
> ```
> 
> This would be easier and clean because sometimes you just want a quick way of getting the result without doing `random(1)[0]` everytime.
> 
> Now that you have mentioned it, I'm not sure wheather to keep the random function as-is or to change it.

i think you missed the point of what i was trying to say, unless there is some **need** to, a function should always return the same type.

for example, if i were to take a number from the user, and get that many tags, i would have to handle it differently depending on what number they pass

```py
def get_tags(num: int) -> List[str]:
    return Tags.random(num)

# vs

def get_tags(num: int) -> List[str]:
    x = Tags.random(num)
    if num == 1:
        x = [x]
    return x
  ```
if you **really** want to handle in-lib, you should probably add another method, that only gets 1 tag

**Comment by scrazzz** [comment] 2022-08-22 16:13
> if you really want to handle in-lib, you should probably add another method, that only gets 1 tag

Yes, you're right. Though I would not know what I would call that method as.

I have planned to not change this method, it'll be as-is.

To clarify @AaronHuston, you should be indexing `Tags.random()` method as mentioned here: https://github.com/scrazzz/redgifs/issues/5#issuecomment-1219638123

**Closed by scrazzz** 2022-08-22 16:13 UTC
Labels: help wanted, good first issue
